#!/bin/bash

### repeatable command lines to produce random trials from a toy model
### Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

n=20
N=5000
seed=123

#-------------------------------------------------

echo "--------------------------------------------------"
echo "m=0.0"
./univariate-exponential -v -n $n -N $N -p -m 0.0 -o m=0d0 -t m=0d0 --seed $seed

echo "--------------------------------------------------"
echo "m=0.1"
./univariate-exponential -v -n $n -N $N -p -m 0.1 -o m=0d1 -t m=0d1 --seed $seed

echo "--------------------------------------------------"
echo "m=0.3"
./univariate-exponential -v -n $n -N $N -p -m 0.3 -o m=0d3 -t m=0d3 --seed $seed

echo "--------------------------------------------------"
echo "m=0.6"
./univariate-exponential -v -n $n -N $N -p -m 0.6 -o m=0d6 -t m=0d6 --seed $seed

echo "--------------------------------------------------"
echo "m=1.0"
./univariate-exponential -v -n $n -N $N -p -m 1.0 -o m=1d0 -t m=1d0 --seed $seed

echo "--------------------------------------------------"
echo "m=3.0"
./univariate-exponential -v -n $n -N $N -p -m 3.0 -o m=3d0 -t m=3d0 --seed $seed
