#!/usr/bin/env python

"""a script to simulate Poissonian sparse X-ray data
"""
__author__ = "Reed Essick (reed.essick@gmail.com)"

#-------------------------------------------------

import os

import numpy as np

from argparse import ArgumentParser

#-------------------------------------------------

parser = ArgumentParser(description=__doc__)

parser.add_argument('-v', '--verbose', default=False, action='store_true')

parser.add_argument('-o', '--output-dir', default='.', type=str)
parser.add_argument('-t', '--tag', default='', type=str)

args = parser.parse_args()

if not os.path.exists(args.output_dir):
    os.makedirs(args.output_dir)

if args.tag:
    args.tag = "_"+args.tag

#-------------------------------------------------

raise NotImplementedError('''\
write:
  - function to draw samples from noise distribution
  - function to draw samples from signal distribution
  - joint likelihood distribution

loop over trials, generating data for each trial (many GTIs)
write these to disk
''')
