#!/bin/bash

./make-data       ### generate synthetic data realizations
./downselect-data ### make basic plots summarizing the detection statistics and downselecting data
./fit-data        ### actually fit the data and determine whether there are biases
